CREATE TABLE `bhav_mcx` (
  `id` int NOT NULL AUTO_INCREMENT,
  `date` date NOT NULL,
  `symbol` varchar(50) NOT NULL,
  `expiry_date` date NOT NULL,
  `open_price` decimal(10,2) DEFAULT NULL,
  `high_price` decimal(10,2) DEFAULT NULL,
  `low_price` decimal(10,2) DEFAULT NULL,
  `close_price` decimal(10,2) DEFAULT NULL,
  `previous_close` decimal(10,2) DEFAULT NULL,
  `volume` int DEFAULT NULL,
  `volume_in_thousands` varchar(50) DEFAULT NULL,
  `value` decimal(15,2) DEFAULT NULL,
  `open_interest` int DEFAULT NULL,
  `date_display` varchar(50) DEFAULT NULL,
  `instrument_name` varchar(50) DEFAULT NULL,
  `strike_price` decimal(10,2) DEFAULT NULL,
  `option_type` varchar(10) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=34834 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;



CREATE TABLE `bhavcopy` (
  `TradDt` date DEFAULT NULL,
  `BizDt` date DEFAULT NULL,
  `Sgmt` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
  `Src` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
  `FinInstrmTp` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
  `FinInstrmId` int NOT NULL,
  `ISIN` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TckrSymb` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `SctySrs` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `XpryDt` date DEFAULT NULL,
  `FininstrmActlXpryDt` date DEFAULT NULL,
  `StrkPric` decimal(18,2) DEFAULT NULL,
  `OptnTp` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FinInstrmNm` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `OpnPric` decimal(18,2) DEFAULT NULL,
  `HghPric` decimal(18,2) DEFAULT NULL,
  `LwPric` decimal(18,2) DEFAULT NULL,
  `ClsPric` decimal(18,2) DEFAULT NULL,
  `LastPric` decimal(18,2) DEFAULT NULL,
  `PrvsClsgPric` decimal(18,2) DEFAULT NULL,
  `UndrlygPric` decimal(18,2) DEFAULT NULL,
  `SttlmPric` decimal(18,2) DEFAULT NULL,
  `OpnIntrst` bigint DEFAULT NULL,
  `ChngInOpnIntrst` bigint DEFAULT NULL,
  `TtlTradgVol` bigint DEFAULT NULL,
  `TtlTrfVal` decimal(18,2) DEFAULT NULL,
  `TtlNbOfTxsExctd` bigint DEFAULT NULL,
  `SsnId` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
  `NewBrdLotQty` int NOT NULL,
  `Rmks` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `Rsvd1` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `Rsvd2` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `Rsvd3` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `Rsvd4` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id` int NOT NULL AUTO_INCREMENT,
  `status` tinyint NOT NULL DEFAULT '0',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=326084 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
